### ISSUE TITLE
Version exception for older versions of Racket?

### ISSUE THREAD

**Issue by countvajhula** [AlexKnauth/kw-utils#5]
I ran into this error on CI for Racket 7.8:

https://github.com/countvajhula/lazytree/runs/7982162597?check_suite_focus=true#step:4:280

Looks like it's because `formals-no-rest` which was [recently added](https://github.com/AlexKnauth/kw-utils/commit/16374d823c002b73436b07aaafa605f5513d5be0) to the repo was introduced to Racket in [this commit](https://github.com/racket/racket/commit/d03456b55e9321d491b5a936cf721466728376e2), which likely means that it was in Racket [beginning 8.0](https://github.com/racket/racket/releases/tag/v8.0).

The typical resolution here is to add [version exceptions](https://docs.racket-lang.org/pkg/getting-started.html#%28part._.Version_.Exceptions%29) for older versions of Racket on the [package page](https://pkgs.racket-lang.org/package/kw-utils).

**Comment by AlexKnauth** [comment]
Or I could stop using `formals-no-rest`. IIRC only thing it's really doing for me that I'm not doing already is duplicate-identifier checking.

**Comment by countvajhula** [comment]
Works for me if you prefer that. I also double-checked and looks like it made it in [in 8.1](https://github.com/countvajhula/lazytree/actions/runs/2915191714).

**Comment by countvajhula** [comment]
Also, if you're interested in preserving compatibility with older versions of Racket, I recommend putting a legacy version in your GA test matrix ([example](https://github.com/countvajhula/lazytree/blob/e9e463c03638a8cd863e232aee72a32655128dda/.github/workflows/test.yml#L15-L22)).

**Comment by AlexKnauth** [comment]
Okay, I'm a bit curious now with the `include:` thing... is it possible to make the test matrix include variants CS and BC for versions where both are available, but only BC for older versions before that?

For another project I've made it cover versions down to `6.6`, but for that project I didn't have both BC and CS variants at all, I didn't know how.

**Comment by AlexKnauth** [comment]
Ah, I found this, I'll try it:
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations

**Comment by countvajhula** [comment]
There's also [this doc on the `include` directive](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude) that suggests that if the "included" key is one of the existing ones in the matrix but it has a distinct value, then it is treated as a unique new combination instead of augmenting an existing combination. So in this case, if you add a `racket-version` that differs from the values in the matrix, you should be able to leave out the variant and I don't think it would add one.

**Comment by AlexKnauth** [comment]
Okay, it now works on versions as far back as 6.6.
